DELIMITER $$

DROP PROCEDURE IF EXISTS `null_redir`.`Test`$$

CREATE PROCEDURE `null_redir`.`Test`()
    /*LANGUAGE SQL
    | [NOT] DETERMINISTIC
    | { CONTAINS SQL | NO SQL | READS SQL DATA | MODIFIES SQL DATA }
    | SQL SECURITY { DEFINER | INVOKER }
    | COMMENT 'string'*/
    BEGIN

SELECT VERSION();

    END$$

DELIMITER ;