CALL Get_Ware();

SELECT * FROM TABLES WHERE TABLE_SCHEMA = '7trav_test';

SHOW INDEX FROM Ware FROM 7trav_test;
SHOW TABLE STATUS FROM 7trav_test;

-- structure table
SHOW CREATE TABLE Ware;

SELECT * FROM TABLE_CONSTRAINTS WHERE TABLE_SCHEMA = '7trav_test';

SHOW TABLE STATUS FROM 7trav_test LIKE 'Ware';
SELECT * FROM REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = '7trav_test' AND TABLE_NAME = 'Ware';
SELECT * FROM REFERENTIAL_CONSTRAINTS WHERE CONSTRAINT_SCHEMA = '7trav_test' AND REFERENCED_TABLE_NAME = 'Ware';

SHOW TABLE STATUS;